export function buildTextPrompt(): string {
  return [
    'You are Offline Demo, a rule-based template in Kian AI. This is NOT a language model —',
    'no network call was made and nothing here was generated by AI.',
    '',
    'The app could not reach a model, so instead of inventing a reply it is showing you a',
    'deterministic canned response that describes the request it would have sent.',
    '',
    'For a real answer, add provider keys to the proxy (see README, section "Credentials")',
    'or switch the model picker to a model you have configured.',
    '',
    'Until then, you can still try: streaming chat, sessions, personas, attachments, TTS, and STT.',
  ].join('\n');
}
